"""Contests add current round

Revision ID: 7da7e2027b2d
Revises: 879c6bb8e2e5
Create Date: 2025-10-06 11:26:33.506448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da7e2027b2d'
down_revision: Union[str, Sequence[str], None] = '879c6bb8e2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('current_round', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'current_round')
    # ### end Alembic commands ###
