"""Users_Chats model remove

Revision ID: e05ec1f935a0
Revises: 8c7e41633a54
Create Date: 2025-10-05 17:42:33.087043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e05ec1f935a0'
down_revision: Union[str, Sequence[str], None] = '8c7e41633a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_chats')
    op.add_column('contests', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contests', 'users', ['creator_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contests', type_='foreignkey')
    op.drop_column('contests', 'creator_id')
    op.create_table('users_chats',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('users_chats_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('users_chats_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name=op.f('users_chats_pkey'))
    )
    # ### end Alembic commands ###
