"""Contests add registration_deadline

Revision ID: e86016819667
Revises: 7da7e2027b2d
Create Date: 2025-10-06 11:59:00.253240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86016819667'
down_revision: Union[str, Sequence[str], None] = '7da7e2027b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'registration_deadline')
    # ### end Alembic commands ###
