"""remove vote model

Revision ID: d480df5ebc63
Revises: 558eb796d5a3
Create Date: 2025-10-05 14:44:04.337974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd480df5ebc63'
down_revision: Union[str, Sequence[str], None] = '558eb796d5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.add_column('matches', sa.Column('votes_user1', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('votes_user2', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'votes_user2')
    op.drop_column('matches', 'votes_user1')
    op.create_table('votes',
    sa.Column('vote_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voted_for_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('votes_match_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voted_for_id'], ['users.user_id'], name=op.f('votes_voted_for_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.user_id'], name=op.f('votes_voter_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id', name=op.f('votes_pkey'))
    )
    # ### end Alembic commands ###
