debug: true

session:
  key: !ENV ${SECRET_KEY}

admin:
  login: !ENV ${ADMIN_LOGIN}
  password: !ENV ${ADMIN_PASSWORD}

web:
  host: 127.0.0.1
  port: 8000
  print: true

sentry:
  dsn:
  env: dev

database:
  host: !ENV ${POSTGRES_HOST}
  port: !ENV ${POSTGRES_PORT}
  user: !ENV ${POSTGRES_USER}
  password: !ENV ${POSTGRES_PASSWORD}
  database: !ENV ${POSTGRES_DB}
  echo: true

bot:
  token: !ENV ${BOT_TOKEN}
  timeout: 25

game:
  voting_time: 10
  registration_time: 15

store: {}
